In [3]:
import cv2
import sys
import os
import numpy as np

strength = 2.0

diffuse = cv2.imread('C:\\Users\\LEE CHANG YOUNG\\Documents\\GitHub\\python_normalmap_test\\normalmap_sample_img\\test_image\\battery.jpg')


In [4]:
average = cv2.cvtColor(diffuse, cv2.COLOR_RGB2GRAY)

In [5]:
average = cv2.normalize(average.astype('float'), None, 0.0, 1.0, cv2.NORM_MINMAX)

In [6]:
sobelx = cv2.Sobel(average, -1, 1, 0, ksize=3)
sobely = cv2.Sobel(average, -1, 0, 1, ksize=3)

In [7]:
ones = np.ones(average.shape)

In [6]:
print(ones)

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


In [7]:
print(sobelx)

[[ 0.00000000e+00 -1.68067227e-02 -3.36134454e-02 ...  1.68067227e-02
   8.40336134e-03  0.00000000e+00]
 [ 0.00000000e+00 -4.20168067e-03 -2.94117647e-02 ... -4.20168067e-03
  -1.68067227e-02  0.00000000e+00]
 [ 0.00000000e+00  4.20168067e-03 -2.10084034e-02 ... -5.04201681e-02
  -7.56302521e-02  0.00000000e+00]
 ...
 [ 0.00000000e+00 -3.36134454e-02  1.38655462e-01 ...  1.68067227e-02
   1.05042017e-01  0.00000000e+00]
 [ 0.00000000e+00 -1.11022302e-16  1.30252101e-01 ...  1.55462185e-01
   1.89075630e-01  0.00000000e+00]
 [ 0.00000000e+00  3.36134454e-02  1.00840336e-01 ...  1.76470588e-01
   2.01680672e-01  0.00000000e+00]]


In [8]:
print(sobely)

[[ 0.          0.          0.         ...  0.          0.
   0.        ]
 [-0.00840336  0.00420168  0.0210084  ...  0.01260504 -0.03361345
  -0.05882353]
 [-0.01680672 -0.0210084  -0.0210084  ... -0.00840336 -0.06722689
  -0.10084034]
 ...
 [-0.02521008 -0.02521008 -0.00420168 ... -0.21008403 -0.0210084
   0.05042017]
 [ 0.22689076  0.2605042   0.26470588 ... -0.0210084   0.01260504
   0.02521008]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]]


In [8]:
n = np.stack((strength*sobelx,strength*sobely, ones), axis=2)

In [9]:
norm =  np.linalg.norm(n, axis=2, keepdims=True)

In [10]:
n = n / norm


In [11]:
n = n*0.5+0.5

In [12]:
normalmap = np.stack((n[:, : , 2], n[:, :, 1], 1.0 - n[: ,: ,0]), axis=2)

In [13]:
normalmap = (normalmap * 255).astype(np.uint8)

In [17]:
save_path = 'C:\\Users\\LEE CHANG YOUNG\\Documents\\GitHub\\python_normalmap_test\\normalmap_sample_img\\result_image.jpg'


In [15]:
cv2.namedWindow("output",cv2.WINDOW_NORMAL)
cv2.resizeWindow("output",600,600)
cv2.imshow("output", normalmap)  # 생성된 노멀맵을 화면에 출력합니다.
cv2.waitKey(0)
cv2.destroyAllWindows()

: 

-1